import React, { useState, useEffect } from 'react';
import { Helmet } from 'react-helmet';
import Header from '../../components/ui/Header';
import ProjectTypeSelector from './components/ProjectTypeSelector';
import ProjectDetailsForm from './components/ProjectDetailsForm';
import ContactInformationForm from './components/ContactInformationForm';
import ProjectRoadmapSummary from './components/ProjectRoadmapSummary';
import ProgressIndicator from './components/ProgressIndicator';
import TrustSignals from './components/TrustSignals';
import Button from '../../components/ui/Button';
import Icon from '../../components/AppIcon';

const ProjectInquiryHub = () => {
  const [currentStep, setCurrentStep] = useState(1);
  const [formData, setFormData] = useState({});
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [showSuccessMessage, setShowSuccessMessage] = useState(false);

  const totalSteps = 4;

  // Auto-save form data to localStorage
  useEffect(() => {
    const savedData = localStorage.getItem('clykur-project-inquiry');
    if (savedData) {
      try {
        const parsed = JSON.parse(savedData);
        setFormData(parsed.formData || {});
        setCurrentStep(parsed.currentStep || 1);
      } catch (error) {
        console.error('Error loading saved form data:', error);
      }
    }
  }, []);

  useEffect(() => {
    if (Object.keys(formData).length > 0) {
      localStorage.setItem('clykur-project-inquiry', JSON.stringify({
        formData,
        currentStep,
        timestamp: Date.now()
      }));
    }
  }, [formData, currentStep]);

  const handleProjectTypeSelect = (type) => {
    setFormData({ ...formData, projectType: type });
  };

  const handleFormChange = (newData) => {
    setFormData(newData);
  };

  const handleNext = () => {
    if (currentStep < totalSteps) {
      setCurrentStep(currentStep + 1);
      window.scrollTo({ top: 0, behavior: 'smooth' });
    }
  };

  const handleBack = () => {
    if (currentStep > 1) {
      setCurrentStep(currentStep - 1);
      window.scrollTo({ top: 0, behavior: 'smooth' });
    }
  };

  const handleScheduleConsultation = () => {
    // Simulate calendar booking
    setIsSubmitting(true);
    setTimeout(() => {
      setIsSubmitting(false);
      setShowSuccessMessage(true);
      // Clear saved data after successful submission
      localStorage.removeItem('clykur-project-inquiry');
    }, 2000);
  };

  const handleDownloadRoadmap = () => {
    // Simulate PDF download
    const element = document.createElement('a');
    element.href = 'data:text/plain;charset=utf-8,' + encodeURIComponent(
      `Project Roadmap for ${formData.projectName}\n\nGenerated by Clykur Portfolio\n\nThis is a preliminary roadmap based on your project requirements. Please schedule a consultation for detailed planning.`
    );
    element.download = `${formData.projectName || 'Project'}-Roadmap.txt`;
    element.click();
  };

  const handleStartOver = () => {
    setFormData({});
    setCurrentStep(1);
    setShowSuccessMessage(false);
    localStorage.removeItem('clykur-project-inquiry');
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const renderCurrentStep = () => {
    switch (currentStep) {
      case 1:
        return (
          <ProjectTypeSelector
            selectedType={formData.projectType}
            onTypeSelect={handleProjectTypeSelect}
          />
        );
      case 2:
        return (
          <ProjectDetailsForm
            formData={formData}
            onFormChange={handleFormChange}
            projectType={formData.projectType}
            onNext={handleNext}
            onBack={handleBack}
          />
        );
      case 3:
        return (
          <ContactInformationForm
            formData={formData}
            onFormChange={handleFormChange}
            onNext={handleNext}
            onBack={handleBack}
          />
        );
      case 4:
        return (
          <ProjectRoadmapSummary
            formData={formData}
            onScheduleConsultation={handleScheduleConsultation}
            onDownloadRoadmap={handleDownloadRoadmap}
          />
        );
      default:
        return null;
    }
  };

  if (showSuccessMessage) {
    return (
      <>
        <Helmet>
          <title>Consultation Scheduled - Clykur Portfolio</title>
          <meta name="description" content="Your consultation has been successfully scheduled. We'll be in touch soon!" />
        </Helmet>
        <Header />
        <div className="min-h-screen bg-background pt-20">
          <div className="max-w-4xl mx-auto px-4 py-16 text-center">
            <div className="w-20 h-20 bg-success rounded-full flex items-center justify-center mx-auto mb-6">
              <Icon name="CheckCircle" size={40} className="text-white" />
            </div>
            <h1 className="text-3xl font-bold text-text-primary mb-4">
              Consultation Scheduled Successfully!
            </h1>
            <p className="text-text-secondary text-lg mb-8 max-w-2xl mx-auto">
              Thank you for choosing Clykur for your project. We've sent a calendar invitation to {formData.email} 
              and will follow up with additional details within 24 hours.
            </p>
            
            <div className="bg-surface border border-border rounded-xl p-6 mb-8 max-w-2xl mx-auto">
              <h3 className="font-semibold text-text-primary mb-4">What happens next?</h3>
              <div className="space-y-3 text-left">
                <div className="flex items-start">
                  <Icon name="Mail" size={16} className="text-secondary mr-3 mt-1 flex-shrink-0" />
                  <div>
                    <p className="text-sm font-medium text-text-primary">Email Confirmation</p>
                    <p className="text-xs text-text-secondary">You'll receive a detailed agenda and preparation guide</p>
                  </div>
                </div>
                <div className="flex items-start">
                  <Icon name="Calendar" size={16} className="text-secondary mr-3 mt-1 flex-shrink-0" />
                  <div>
                    <p className="text-sm font-medium text-text-primary">Calendar Invitation</p>
                    <p className="text-xs text-text-secondary">Meeting link and dial-in details included</p>
                  </div>
                </div>
                <div className="flex items-start">
                  <Icon name="FileText" size={16} className="text-secondary mr-3 mt-1 flex-shrink-0" />
                  <div>
                    <p className="text-sm font-medium text-text-primary">Project Roadmap</p>
                    <p className="text-xs text-text-secondary">Detailed PDF sent to your email within 2 hours</p>
                  </div>
                </div>
              </div>
            </div>

            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button
                variant="primary"
                onClick={handleStartOver}
                iconName="Plus"
                iconPosition="left"
              >
                Start Another Project
              </Button>
              <Button
                variant="outline"
                onClick={() => window.location.href = '/portfolio-gallery'}
                iconName="Eye"
                iconPosition="left"
              >
                View Our Work
              </Button>
            </div>
          </div>
        </div>
      </>
    );
  }

  return (
    <>
      <Helmet>
        <title>Project Inquiry Hub - Start Your Digital Transformation | Clykur Portfolio</title>
        <meta name="description" content="Begin your digital transformation journey with Clykur. Get a custom project roadmap, timeline estimates, and transparent pricing for your application development needs." />
        <meta name="keywords" content="project inquiry, digital transformation, app development, web development, consultation, project roadmap" />
        <meta property="og:title" content="Project Inquiry Hub - Start Your Digital Transformation" />
        <meta property="og:description" content="Get a custom project roadmap and consultation for your digital transformation needs." />
        <meta property="og:type" content="website" />
      </Helmet>
      
      <Header />
      
      <div className="min-h-screen bg-background pt-20">
        {/* Hero Section */}
        <div className="bg-gradient-to-br from-primary to-surface py-16">
          <div className="max-w-6xl mx-auto px-4 text-center">
            <h1 className="text-4xl md:text-5xl font-bold text-text-primary mb-6">
              Let's Build Something <span className="text-gradient">Amazing</span> Together
            </h1>
            <p className="text-xl text-text-secondary max-w-3xl mx-auto mb-8">
              Get a custom project roadmap, realistic timeline estimates, and transparent pricing. 
              Our intelligent inquiry system helps us understand your needs and provide immediate value.
            </p>
            
            <div className="flex flex-wrap justify-center gap-6 text-sm text-text-secondary">
              <div className="flex items-center">
                <Icon name="Clock" size={16} className="mr-2 text-secondary" />
                <span>5-minute form</span>
              </div>
              <div className="flex items-center">
                <Icon name="FileText" size={16} className="mr-2 text-secondary" />
                <span>Instant roadmap</span>
              </div>
              <div className="flex items-center">
                <Icon name="Calendar" size={16} className="mr-2 text-secondary" />
                <span>Free consultation</span>
              </div>
              <div className="flex items-center">
                <Icon name="Shield" size={16} className="mr-2 text-secondary" />
                <span>100% confidential</span>
              </div>
            </div>
          </div>
        </div>

        {/* Progress Indicator */}
        <div className="py-8 bg-background">
          <ProgressIndicator currentStep={currentStep} totalSteps={totalSteps} />
        </div>

        {/* Main Form Content */}
        <div className="py-12 bg-background">
          <div className="max-w-6xl mx-auto px-4">
            {renderCurrentStep()}
            
            {/* Step 1 Navigation */}
            {currentStep === 1 && formData.projectType && (
              <div className="text-center mt-8">
                <Button
                  variant="primary"
                  onClick={handleNext}
                  iconName="ArrowRight"
                  iconPosition="right"
                  size="lg"
                >
                  Continue to Project Details
                </Button>
              </div>
            )}
          </div>
        </div>

        {/* Trust Signals */}
        <TrustSignals />

        {/* Footer CTA - minimal boxed container */}
        <div className="py-12">
          <div className="max-w-4xl mx-auto px-4">
            <div className="border border-border rounded-xl p-6 bg-background">
              <h3 className="text-2xl font-bold text-text-primary mb-3 text-center">Questions About the Process?</h3>
              <p className="text-text-secondary mb-6 text-center">
                Our project inquiry system provides immediate value and clarity. No pressure—just helpful guidance to inform your decision.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <Button
                  variant="secondary"
                  onClick={() => window.location.href = '/contact-engagement-hub'}
                >
                  Contact Us Directly
                </Button>
                <Button
                  variant="outline"
                  onClick={() => window.location.href = '/portfolio-gallery'}
                >
                  View Our Portfolio
                </Button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default ProjectInquiryHub;